name: ç´«ç™½èœ
description: á¥¬ğŸ˜‚á­„æˆå¹´äººçš„ä¸–ç•Œï¼Œé‡‘é’±æ˜¯æ´»ç€çš„ç­¹ç ï¼  <br />
             å¹¶éå¤šçˆ±é’±ï¼Œè€Œæ˜¯æ²¡é’±çœŸçš„ä¸è¡Œï¼á¥¬ğŸ˜‚á­„  
meta_description: "ç´«ç™½èœï¼Œzibaicaiï¼ŒYour New Jekyll Site, "

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 10
domain_name: 'zibaicai.com'
# google_analytics: 'UA-XXXXXXXX-X'
# disqus: false
# disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://zibaicai.com'
author:         'ç´«ç™½èœ'
# authorTwitter:  'YourTwitterUsername'

permalink:       /:title.html

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

theme: jekyll-theme-cayman
